### ISSUE TITLE
Support Output of Raw Bytes from the Subprocess

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/snekbox#103]
Currently, all output is interpreted as Unicode text. Supporting byte output would allow a much more diverse range of things that could be returned e.g. images and sound. I think it makes sense to maintain a single endpoint and simply add a parameter to change from text to byte mode, but I'm still open to discussion on making it a separate endpoint.

Since the API uses JSON, the bytes would have to be base64-encoded, unless someone has a better alternative (which could perhaps also be a good argument for making it a separate endpoint).

Raising the output limit from 1 MB should be considered for byte output, if not all output. 8 MB sounds sensible and makes sense in the context of Discord attachments (even though Python Discord does have a higher limit thanks to boosts). It'd be useful to have someone from @python-discord/devops consult on an appropriate limit.

**Comment by ChrisLovering** [comment]
I guess we could leverage the use of an `Accept` header in the post call to determine what to send back, so that it's backwards compatible, but also gives the option to accept an octet stream, or base64 encoded bytes.

**Comment by MarkKoz** [comment]
@ChrisLovering That is an interesting idea, but the response also needs to include the return code of the process. I don't see how that could work.

**Comment by MarkKoz** [comment]
@python-discord/devops Can you advise on a reasonable output limit? Compressing responses is also an option (https://github.com/willnewton/falcon-compression), but not sure if it's necessary. What do you think?

**Comment by ChrisLovering** [comment]
Anywhere 5-10MB seems reasonable to me

**Comment by MarkKoz** [comment]
And what of compression?

**Comment by HassanAbouelela** [comment]
We have more CPU resources than we can use so if you think it'll prove useful, compression sounds fine.
