### ISSUE TITLE
Support File I/O

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/snekbox#114]
Several users have expressed a desire to interact with files with their executed code. I believe such feature is in scope and that it would be a great feature. Supporting it would require a way to mount an isolated, size-capped r/w directory for each NsJail instance. Implementation details need to be investigated to determine the feasability of this feature.

**Comment by zachkaupp** [comment]
How would they send the files with their code? (Not related to NsJail, I just see it as another issue that would need to be addressed)

**Comment by MarkKoz** [comment]
That's not a big concern on this end (maybe that's what you were trying to state with "not related to NsJail"). Files would be sent by adding a list of key-value pairs to the request format, where the key is the file path and the value is the content. Since the request is in JSON, I suppose file content has to be encoded e.g. in base64. If anyone has better ideas, feel free to share.

**Comment by MarkKoz** [comment]
That being said, I would be okay with something narrower in scope that doesn't even support sending files. Users could still write new files through their Python code.

**Comment by akabinds** [comment]
I would be open to helping develop this feature, if it is still being considered.

**Comment by MarkKoz** [comment]
@akabinds Yes, that would be a welcome contribution. However, how to accomplish this has not been researched yet; that's probably where you should start. Maybe it should be an in-memory file system (tmpfs) rather than on disk?

Here is what I believe needs to be implemented:

* Each eval mounts a new read-write directory.
* It is initially empty.
* It is set as the CWD for the eval.
* It is isolated, meaning evals from other requests cannot access this directory (neither read nor write).
* It has a size cap (let's just say 10 MB for now; it should be configurable though).
* It is deleted when the eval ends.

**Comment by akabinds** [comment]
> @akabinds Yes, that would be a welcome contribution. However, how to accomplish this has not been researched yet; that's probably where you should start. Maybe it should be an in-memory file system (tmpfs) rather than on disk?
> 
> Here is what I believe needs to be implemented:
> 
> * Each eval mounts a new read-write directory.
> * It is initially empty.
> * It is set as the CWD for the eval.
> * It is isolated, meaning evals from other requests cannot access this directory (neither read nor write).
> * It has a size cap (let's just say 10 MB for now; it should be configurable though).
> * It is deleted when the eval ends.
> 
> Sending files to snekbox is going to be out of scope for this issue. That idea can be revisited separately.

I do also agree that it should be something that is in-memory. I will start research ASAP.
