### ISSUE TITLE
Cgroup PermissionError

### ISSUE THREAD

**Issue by BLANK-TH** [python-discord/snekbox#116]
I'm not particularly sure if this is the proper place to ask but I'm having issues running snekbox. It works fine on my local PC (Windows) but when I try and run it on my VPS (Linux, Debian) I get a PermissionError while trying to run code. It seems to have something to do with cgroup but I'm not particularly experienced with that so I can't figure out how to fix it. Traceback that happens each time I try and run code on it:

```
Traceback (most recent call last):
  File "/snekbox/snekbox/api/resources/eval.py", line 87, in on_post
    result = self.nsjail.python3(code, py_args=args)
  File "/snekbox/snekbox/nsjail.py", line 190, in python3
    cgroup = self._create_dynamic_cgroups()
  File "/snekbox/snekbox/nsjail.py", line 96, in _create_dynamic_cgroups
    (mem / "memory.limit_in_bytes").write_text(mem_max, encoding="utf-8")
  File "/usr/local/lib/python3.9/pathlib.py", line 1275, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.9/pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.9/pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/sys/fs/cgroup/memory/snekbox-6a523f3a-3eaf-4da0-8e8f-dcfd0e0f425b/memory.limit_in_bytes'
```

Initially /sys/fs/cgroup/memory didn't exist, after searching around to no avail I just made the folder with mkdir, after which it got populated with various other stuff but not any folders under snekbox.

If I could get any help on this from people with more experience than me, it'd be greatly appreciated. And in the case that it's just a distro issue (which I don't think it is), I'm more than happy to just swap distros on my server.

**Comment by MarkKoz** [comment]
Your VPS might be using cgroupv2 by default, which snekbox currently doesn't support. You can check if cgroup or cgroup2 is mounted by looking in `/etc/mtab`.

**Comment by BLANK-TH** [comment]
Yup, looks like it's using cgroup2
![](https://blank.life-is-pa.in/5aMhvRbwh.png)

How should I go about changing it?

**Comment by MarkKoz** [comment]
As documented [here](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#openstack-cgroups), you can set a couple of kernel parameters to go back to the v1 hierarchy. If you're curious what exactly those parameters do, they're documented in the systemd manpage. Snekbox really should be updated to support v2 though...

**Comment by BLANK-TH** [comment]
Nice! That worked, thanks a lot for your help.
