### ISSUE TITLE
Passing arguments when running from command line fails

### ISSUE THREAD

**Issue by wookie184** [python-discord/snekbox#124]
When running `python -m snekbox 'print("hello world!")' --time_limit 0` (documented [here](https://github.com/python-discord/snekbox/blob/main/DEVELOPING.md)) I get this error:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/snekbox/snekbox/__main__.py", line 28, in <module>
    main()
  File "/snekbox/snekbox/__main__.py", line 23, in main
    result = NsJail().python3(args.code, *args.nsjail_args)
TypeError: NsJail.python3() takes 2 positional arguments but 4 were given
```
This is because of https://github.com/python-discord/snekbox/pull/108 changing the signature for the `NsJail.python3` function

This is the relevant line that needs changing:
https://github.com/python-discord/snekbox/blob/dc9a9e0aa9c0d56b8cbfd2e3f84f011ce0e3201d/snekbox/__main__.py#L23

The fix should be simple, just pass in the keyword argument `nsjail_args`, although do we want to try and handle setting `py_args` from the command line too? If someone suggests a suitable interface for that i'd be happy to add it, otherwise i'd be happy to just fix the passing of nsjail arguments.

**Comment by MarkKoz** [comment]
> do we want to try and handle setting py_args from the command line too?

I'd like to, but I cannot think of a good way to do it. The only options I can think of are:

1. Specify all the arguments as a quoted string
2. Have some delimiter word/character between the nsjail and py arguments, then use that to split the unknown arguments list.

**Comment by wookie184** [comment]
> > do we want to try and handle setting py_args from the command line too?
> 
> I'd like to, but I cannot think of a good way to do it. The only options I can think of are:
> 
> 1. Specify all the arguments as a quoted string
> 2. Have some delimiter word/character between the nsjail and py arguments, then use that to split the unknown arguments list.

I think 1 seems a bit more intuitive and would be alright. We could add `--time_limit` as a separate shorthand argument if it's used most commonly (not sure if it is)

**Comment by MarkKoz** [comment]
> I think 1 seems a bit more intuitive and would be alright. 

Better than nothing.

> We could add --time_limit as a separate shorthand argument if it's used most commonly (not sure if it is)

I don't think it's necessary. The current approach for NsJail args seems fine.
