### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/snekbox#152]
When might we expect snekbox to have a 3.11 build?

**Comment by HassanAbouelela** [comment]
The 3.11 image from the 3.11 branch is published (manually currently), and we’ll probably upgrade main soon as long there aren’t any dependency issues or similar.

**Comment by onerandomusername** [comment]
That image currently uses the release candidates for 3.11, I don't see one using 3.11 final

**Comment by HassanAbouelela** [comment]
For all intents and purposes, that shouldn't matter, however we'll use final when updating main.
