### ISSUE TITLE
Timing code execution?

### ISSUE THREAD

**Issue by IamMusavaRibica** [python-discord/snekbox#162]
I checked the source code for both api endpoint and nsjail wrapper, but i haven't seen a way to actually measure how long the code took to run. Would this be hard to implement?

**Comment by MarkKoz** [comment]
Hi, the API supports arbitrary arguments to the `Python` subprocess. You can use [`timeit`](https://docs.python.org/3/library/timeit.html#timeit-command-line-interface) from the Python Standard Library to time code execution. The API docs have an [example](https://github.com/python-discord/snekbox/blob/6266a62f66b835b7f6cb87b2a53f00295776c274/snekbox/api/resources/eval.py):

```py
>>> {
...     "input": "[i for i in range(1000)]",
...     "args": ["-m", "timeit"] # This is optional
... }
```

Did you have something else in mind?

**Comment by IamMusavaRibica** [comment]
I was about to edit the code (through AST or directly) adding `import time` and `START_TIME = time.perf_counter()` at the beginning (obviously would use a different variable name), and `print("\n", time.perf_counter() - START_TIME, flush=True)` at the end then reading the last line of stdout, but this is just ugly and would not work if there was an error above in the code.
However I never used timeit from command line, I'll try to use it and let you know how it goes
Thanks, closing this for now
