### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ImInTheICU** [python-discord/snekbox#164]
![image](https://user-images.githubusercontent.com/111275373/210182161-94e89227-77c2-4ee7-b7a2-ac464f369bb0.png)

**Comment by MarkKoz** [comment]
Hi, this seems like an issue with Docker on your system that is not specific to snekbox. Thus, this is not an appropriate place to get support for that issue. You're welcome to join Python Discord and get support there, or another community like the Docker forums or StackOverflow.
