### ISSUE TITLE
Testing Provisions

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/snekbox#28]
As you may know, NsJail complicates things when testing locally because it requires root to run. The simplest approach is to basically offer nothing, but I don't think people are too keen on installing NsJail themselves and running as root.

I was thinking of running tests in a Docker container. Currently, getting files from the container is only needed for working with coverage.py. There are two options to getting the outputs of coverage:

1. Mount the local snekbox repository into the container using a bind mount.
2. No bind mount or volumes. Just use `docker cp` to copy files

Either way, the files will be owned by root. However, this can easily be fixed with `chown`. I already had a lot of stuff figured out for testing in containers it works quite well. Though file permissions seem easy to fix, the issue made me start reconsidering the entire container approach.

**Comment by jchristgit** [comment]
I think Docker is overcomplicating this, and Docker also needs root. If you don't give it root, there's the `docker` group, but at the end of the day Docker is still running as root. I think adding Docker will just add a layer of indirection and testing on the host seems preferable considering we're not modifying the NSJail installation

**Comment by MarkKoz** [comment]
That's something I didn't consider. I'll try to make a script for local testing, if one will even be needed.

**Comment by MarkKoz** [comment]
@jchristgit But do you think it may be cumbersome to install NsJail? Not all distros have packages for it. Speaking of which, testing locally wouldn't be possible on macOS or Windows, but it could be with Docker.

**Comment by MarkKoz** [comment]
Well that last comment was a bit prophetic.

Turns out the logging format in NsJail changed since the latest release. Since the base docker image clones from master rather than a release tag, the logging parser will not work with the release. So my options are either to rewrite the logging parser to work with release or try to install NsJail from master.

I could install the release fine on Arch but I have errors when building from master. To make matters slightly worse, the git version of NsJail on AUR was outdated so it didn't include the bison dependency. Not a great experience.

**Comment by MarkKoz** [comment]
Right, I just went with Docker. Feel free to re-open if there are objections.
