### ISSUE TITLE
Non-core library module support

### ISSUE THREAD

**Issue by sco1** [python-discord/snekbox#3]
I'm not sure what's involved to allow for this, but it would be nice to be able to whitelist some of the more common community packages (e.g. `numpy`, `pandas`, etc.) for use inside of the snekbox.

Thoughts?

-----

@MarkKoz's edit:

If you have suggestions for package you can write them in this issue or just open a PR to add them in. All you need to do is add them like you would any other dependency to pipenv. Just make sure you pin the version and that the lock file gets updated. A short justification for your suggestions would be appreciated.

**Comment by jos-b** [comment]
I'll look into how we'd go about achieving this. I wonder if just installing modules into the Pipfile would allow them to be accessed in the container.

**Comment by jos-b** [comment]
Actually, we may need to be careful about this one because some modules may not work with the limits have have operating on the execution environment.

**Comment by jos-b** [comment]
Okay so @sco1, regarding how much work is required to install dependencies, from what I can see all we need to do to get external module support is install them in the Pipfile.

As you can see if I import `pika` (our rabbitmq library, installed in container) here, it works:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/20439493/51076783-2fd5f500-1695-11e9-8cc7-e9a272aa1cb1.png">

We can test this with other libraries and see if they work inside our environment.

**Comment by jos-b** [comment]
Few ideas of modules to add:
- numpy
- scipy
- pandas

Obviously we can't have things like requests because we deny network access. Also nothing GUI related although in future maybe we could have some integration with things like `matplotlib` so we could send graphs generated to Discord.

**Comment by sco1** [comment]
Those would probably cover the vast majority of things that get asked that we could reasonable accommodate in a jailed sandbox.

A couple more to toss in that probably don't get used nearly as much but do occasionally have very helpful things to show off:

- sympy
- fuzzywuzzy (w/python-Levenshtein)
- python-dateutil
- pendulum
- arrow
- yarl

**Comment by scragly** [comment]
I'd like to second:
`pendulum` (which has the bonus of adding `pytz` to the list)
`python-dateutil`
`fuzzywuzzy`

I'd also like to add `lxml` to the list if possible.

**Comment by jos-b** [comment]
@scragly what would exactly be the point of lxml? Where would users get XML data from (considering that internet access is blocked)

**Comment by scragly** [comment]
That's an excellent point; there is none in that case. I retract my previous comment. :rofl:

**Comment by jos-b** [comment]
I’m also a little bit confused about why we would need levenshtein or fuzzywuzzy stuff. I don’t see any immediate use cases but if someone else could provide one then I’d be fine with that.

**Comment by sco1** [comment]
It's come up occasionally in the help channels, data science, and AoC.

**Comment by GhostofGoes** [comment]
While I'd love to +1 `lxml`, there are just too many things that could go wrong without much benefit in return.

**Comment by GhostofGoes** [comment]
Another addition: `dataclasses`

Backport of dataclasses from Python 3.7, since snekbox is on Python 3.6.

**Comment by scragly** [comment]
As a sidenote on the above `dataclasses` suggestion, snekbox is now Python 3.7 so it's included :smile:

**Comment by GhostofGoes** [comment]
Some more additions:
* `PyYAML`
* `toml`
* `attrs`

**Comment by Akarys42** [comment]
I'm sure the guys at #esoteric-python would love to see `forbiddenfruit` to be added, and tbh that would allow us to do some cool things 😁

**Comment by martmists** [comment]
out of curiosity, why do packages need to be added on the codebase rather than just having a config with allowed modules?

**Comment by sco1** [comment]
Because nobody has written a feature that allows for the specification of packages in a config file rather than pulling directly from the project’s dependencies

**Comment by martmists** [comment]
looks to me like a simple requirements-exposed.txt or something would do the trick

**Comment by MarkKoz** [comment]
Perhaps. I could see the benefit in not having to install those while developing. However, a `requirements.txt` would mean foregoing any sort of locking mechanism like what pipenv provides. I don't mind since these packages aren't crucial to the basic Python eval working. However, some sub dependencies may conflict with the sub dependencies in the Pipfile.lock.

Ultimately I don't feel a strong need to do anything different. Adding to a Pipfile is simple and good enough given how little maintenance and development this project sees.

**Comment by martmists** [comment]
Dependencies can be locked in a requirements.txt format just fine, following [PEP 440](https://www.python.org/dev/peps/pep-0440/)

**Comment by MarkKoz** [comment]
Yes, but that means sub dependencies have to be in that file too (I suppose there could be a second `requirements.txt` for those...) How would sub dependencies get locked? Manually? - too tedious. `pip freeze` will have a mix of those and stuff from the Pipfile so that's not great. This is all just in my head so let me know if I am wrong.

**Comment by sco1** [comment]
Merged by #51
