### ISSUE TITLE
Improper use of exit()

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/snekbox#4]
I've noticed some instances of `exit(0)` and `exit(1)` used, which is bad practice as noted in the official docs [here](https://docs.python.org/3.6/library/constants.html#constants-added-by-the-site-module).

>The site module (which is imported automatically during startup, except if the -S command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and **should not be used in programs.**

`raise SystemExit` for example, should be used in its place. If given no arguments, it defaults to `None`, which in turn defaults to an exit status of 0. You can do `raise SystemExit(1)` in place of `exit(1)`.

**Comment by MarkKoz** [comment]
The code in which the `exits()` are present is being removed so this issue is no longer relevant.
