### ISSUE TITLE
Session mode

### ISSUE THREAD

**Issue by gdude2002** [python-discord/snekbox#48]
**This is further to the discussions in #meta and the 2019 Hacktoberfest channel, and https://github.com/python-discord/site/issues/210**

It would be excellent if Snekbox supported a kind of "session mode". Such a mode would allow one to run a persistent Python process in order to serve up a Python REPL or other long-running interactive application. There are some hang-ups to this approach, however..

## Shared Processes

Having Python processes that are shared between multiple sessions is probably not possible for a `code`-based REPL, as it's pretty easy to escape the `code` session and mess with the process or other sessions running in the process.

This means that running a process per-REPL with some kind of time limit or max process limit or _something_ is probably the best approach, but this could get heavy on resources if we're not careful

lemon suggested looking at [PEP 0554](https://www.python.org/dev/peps/pep-0554/) on Discord, which could be very useful for an eventual implementation when it comes to shared processes.

## Worker Routing

The current design of Snekbox makes routing to specific workers impossible, and they don't have a mechanism of communicating with each other in order to route to the correct Python process. Additionally, Gunicorn does not have any way to route requests to specific workers - it's a [fundamental part of how Gunicorn works](https://github.com/benoitc/gunicorn/issues/183#issuecomment-904618) that prevents us from doing this.

That said, there are a few approaches I think we could take.

1. A separate daemon could be run that supports asynchronous access and dispatches to persistent processes running under nsjail as required
1. Falcon could be dropped and replaced with something that is designed with asynchronous programming in mind and is intended to be run as a single worker
1. REPL scope could be serialised and stored in the database somehow, and reloaded on each request - but this could make operations very slow indeed

---

I'm entirely unsure what the best approach to this would be, however. The nature of webapps means that you usually distribute load between workers in order to keep things fast, but doing that means you lose a way to route to the same worker for any set of requests.

Does anyone have any comments on this?

**Comment by gdude2002** [comment]
On @lemonsaurus' advice, I decided to look into how repl.it might meet our needs.

## Suitability

I think repl.it would be able to handily meet all of our needs - it supports once-time program execution, as well as websockets for interactive sessions. It appears to have a comprehensive API too, but I'm unable to get much info on that (see below).

## API

While the API appears to be comprehensive [from what I can find](https://repl.it/site/blog/api-docs), it's stated on the [main API page](https://repl.it/site/api) that they're not currently accepting more customers as they'd like to focus on their classroom offering.

Theri AP

They only offer a JavaScript library, but their API page states:

> If you need libraries in other languages, please get in touch with us.

That said, we could probably write our own without too much difficulty.

As for the Classroom offering, there is [a ton of stuff it can be used for](https://repl.it/site/classrooms), but none of it would integrate with our site. It could still be useful for us, though. Their [pricing page](https://repl.it/site/pricing) has a free offering, and it also states that they have a higher tier K-12 offering for schools and non-profits - so that might be worth looking at as well.

Either way, if we can get some kind of API access, we should have no trouble integrating this into our systems.

## Use-cases

I've come up with a list of possible use-cases, based on discussions with users and staff over my time with PyDis, plus my own thoughts and experiences with other communities and services.

* Snekbox in its current state could easily be replaced by repl.it as a provider for the bot's eval command
* Repl.it could also support live interactive sessions - so REPL support could be added to the bot
* The site could integrate repl.it for a live REPL or one-time file runs, with a bunch of possible uses:
    * Code-along sessions
    * Challenges to be evaluated via repl.it
    * Execution of code jam qualification tasks
    * Collaborative coding, eg for helpers to provide support

There's probably plenty of extra use-cases here that I'm not thinking of as well.

---

I haven't yet explored other third-party alternatives to this, but repl.it does seem like an extremely suitable solution.

**Comment by lemonsaurus** [comment]
good write-up. I'll get in touch with them.

**Comment by lemonsaurus** [comment]
Okay, so word back from repl.it is:

They are currently working on opening up their API, and this will be out soon:tm: .

Meanwhile, if we're in a hurry, we can port this npm package: https://www.npmjs.com/package/@replit/crosis

They warn that this might not be that easy, and have sent over the following docs that might be of use:
https://multiplayer-blog-docs.turbio.repl.co/protov2
https://multiplayer-blog-docs.turbio.repl.co/services

They've also provided a way of generating a token to be used with this system, which I won't post here because this is a public repo.

I'm tempted to suggest we should just let this wait until the API is available, in that case. They've said they will contact me once this happens. Thoughts?

**Comment by gdude2002** [comment]
Hmm, I think you might be right on waiting. That `goval` protocol seems to be too complex to implement ourselves for this specific use-case - even though it seems like they've written a protobuf so it shouldn't be _too_ difficult to port, it seems like a lot of maintenance overhead.

If they're working on it already, might as well let them instead of doing it ourselves and then dumping that code later, right?

**Comment by MarkKoz** [comment]
This hasn't gone anywhere, and I don't feel it's the direction the eval feature on the bot, let alone snekbox, should go in anyway.
