### ISSUE TITLE
stderr coming before stdout despite program output order

### ISSUE THREAD

**Issue by bast0006** [python-discord/snekbox#56]
Sometime between Nov 11 and now, the output behavior of snekbox changed. Previously, code like this:
```
print(1)
raise ValueError()
```
Would reflect stderr and stdout in the output order (that is, the "1" in the output would come before the traceback). Sometime between Nov 11 and late Dec this behavior changed, with stderr coming before stdout in most (all?) cases. This is probably related to the change between ash and bash in 93dab0fa061fdfcf3fdb59210a220ae01c3b4a2e, since bash has buffered outputs by default that have caused this issue in other situations (unrelated to python). 

The simple exception case is not particularly a problem, but since the `logging` framework outputs to stderr by default this can break code that mixes print() and logging. 

Running python within nsjail unbuffered (adding "u" to the "-Iq" in nsjail.py) fixes the issue. But there may be better solutions (stdbuf, a nsjail parameter I'm unfamiliar with)

**Comment by MarkKoz** [comment]
Did you want to work on it?

**Comment by bast0006** [comment]
No, I don't feel like I understand the involved technologies well enough--most of my experience is outside the devops area, and I feel like this is pretty squarely in that direction. The core of the issue is that buffering is now occurring when there wasn't any before, but there's a large variety of solutions between shells, shell configuration, python configuration, and probably more I'm unaware of. I'm sure someone else has a better view of what could be done than I do.

**Comment by MarkKoz** [comment]
That's fine. I'll take care of it then.

I don't think it's a shell issue because I don't think NsJail uses a shell to create the Python process. However, it could be related to the switch to Debian. I don't know why making it unbuffered fixes it, but it works so I'll go with it. I also tried `bufsize=0` for `Popen`, which makes the pipe unbuffered, but that didn't help.
