### ISSUE TITLE
Improve non-developer access

### ISSUE THREAD

**Issue by makusu2** [python-discord/snekbox#57]
At the moment, the only way to use snekbox is to follow the instructions in the README. It would be nice if there were also instructions on how to quickly get a working container up and running, even if it's just a script, although it'd be better if there were instructions on how to use the image on the Docker hub.

**Comment by makusu2** [comment]
```bash
docker pull pythondiscord/snekbox-base \
  && docker run -d --privileged --hostname pdsnk \
    --init --ipc="none" -p8060:8060 pythondiscord/snekbox
```

Something like that in the README. We should at least include the `run` flags. 

I also made the change I suggested in https://github.com/python-discord/snekbox/issues/58; if that's bad, feel free to remove `-p8060:8060` and add `--network="host"`

**Comment by jos-b** [comment]
I don't understand why you are pulling snekbox-base here?

**Comment by jos-b** [comment]
Also while we could simplify things somewhat this isn't the type of docker container where you just boot it up and get a web interface, it is an API so some sort of programming will always be required.

We do already have instructions on how to use the image in the README:

> # HTTP REST API
>
> Communication with snekbox is done over a HTTP REST API. The framework for the HTTP REST > API is Falcon and the WSGI being used is Gunicorn. By default, the server is hosted on 0.0.0.0:8060 with two workers.
> 
> See snekapi.py and resources for API documentation.

Which links two useful code snippets where snekbox is used.

**Comment by makusu2** [comment]
Oops, sorry, snekbox-base was a typo, should've been just snekbox. 

Once snekbox is up and running, I agree, there are plenty of instructions on how to communicate with it. This is more about how to get the docker container running. This might be more of an issue for docker hub, but I'm not sure if that has an issue system :man_shrugging: 

I'm not sure why you say you can't just boot it up; isn't that what the snippet I provided does?

**Comment by MarkKoz** [comment]
This is a valid concern; I agree it should be added. One shouldn't have to resort to the development guide if one is not interested in contributing. The current steps involve cloning the repo and building the Docker images, but that's complicated relative to what you've shown.
