### ISSUE TITLE
Don't run in host mode

### ISSUE THREAD

**Issue by makusu2** [python-discord/snekbox#58]
Network mode is currently set to "host". That's considered pretty insecure; instead, we should just connect port 8060 to the host. I tried that way and it worked for me, is there a different reason we should be using host mode?

**Comment by jos-b** [comment]
Are you referring to the docker-compose being set to host?

**Comment by jos-b** [comment]
I've just checked how we are deploying this and we actually create our own network which we then connect containers to (if you see bot it sends a request to `http://snekbox:8060`).

I believe it is set to host here purely for development purposes, deployment is not intended to be carried out through docker-compose.

**Comment by makusu2** [comment]
Yeah, I was referring to docker-compose. This is more for people who want to run snekbox themselves; the only source of information on how to handle the network (assuming they aren't too familiar with Docker) is the docker-compose file, which has network mode set to host. 

Maybe this should be closed and added in https://github.com/python-discord/snekbox/issues/57, since that's about how people who want to run snekbox themselves can do so.

**Comment by MarkKoz** [comment]
No reason in particular I can think of, but @scragly is the one responsible for that change (it used to map ports back when it still used RMQ and Flask).

**Comment by scragly** [comment]
Yeah, I probably just never changed it from my own janky dev setup at the time. It can be set back to specific ports.
