### ISSUE TITLE
Support for adding more dependencies without forking

### ISSUE THREAD

**Issue by nottheswimmer** [python-discord/snekbox#82]
Sorry if there's a way to do this that I'm not realizing, but if there is it should be documented. I see that I could fork this image and provide my own Pipfile, but is there any way that I can add custom dependencies to the out-of-the-box solution (e.g. through passing some parameters to the run command ideally)?

**Comment by MarkKoz** [comment]
You can use `docker exec` to run `pip install ...` within your running container. Keep in mind packages installed this way won't be part of the image; if the container is deleted, then so will the extra packages you installed.

**Comment by MarkKoz** [comment]
#87 added instructions for how to do this. It's proven to be a viable solution since we do something similar in production now to install the packages we want (#87 no longer puts our packages in the Docker image).
